export const
  SHOW_VISBLE_BOX = "BOX:SHOW_VISIBLE_BOX",

  SET_RED_MARKER = "MARKER:SET_RED_MARKER",

  SET_COLLAPSED_INFO_BOX = "INFO_BOX:SET_COLLAPSED",

  SET_POPUP_RIGHT_CLICK = "POPUP:SET_POPUP"