export const
  SHOW_NAVIGATION_BOX = "BOX:SHOW_NAVIGATION_BOX",

  NAVIGATION_FROM_REQUEST = "LOCATION:NAVIGATION_FROM_REQUEST",

  NAVIGATION_TO_REQUEST = "LOCATION:NAVIGATION_TO_REQUEST",

  NAVIGATION_REQUEST = "LOCATION:NAVIGATION_REQUEST",
  NAVIGATION_SUCCESS = "LOCATION:NAVIGATION_SUCCESS",
  NAVIGATION_FAIL = "LOCATION:NAVIGATION_FAIL",

  SWAP_REQUEST = "LOCATION:SWAP_REQUEST",

  NAVIGATION_SELECT_RESULT_REQUEST = "LOCATION:SELECT_RESULT_REQUEST",
  NAVIGATION_SELECT_RESULT_SUCCESS = "LOCATION:SELECT_RESULT_SUCCESS",

  CLEAR_RESULT_REQUEST = "LOCATION:CLEAR_RESULT_REQUEST",

  CLEAR_REQUEST = "LOCATION:CLEAR_REQUEST",

  TYPE_INPUT = "TYPE_INPUT",
  TYPE_LATLONG = "TYPE_LATLONG",
  INFO_RESTAURANT = "INFO_RESTAURANT"