export const
    SEARCH_REQUEST = "SEARCH:SEARCH_REQUEST",
    SEARCH_SUCCESS = "SEARCH:SEARCH_SUCCESS",

    SEARCH_CLEAR_REQUEST = "SEARCH:CLEAR_REQUEST",

    SEARCH_AROUND_REQUEST = "SEARCH:SEARCH_AROUND_REQUEST",
    SEARCH_AROUND_SUCCESS = "SEARCH:SEARCH_AROUND_SUCCESS",

    CLEAR_SEARCH_AROUND_REQUEST = "SEARCH:CLEAR_SEARCH_AROUND_REQUEST",
    SELECT_AROUND_PLACE_MARKER = "SELECT_AROUND_PLACE_MARKER_REQUEST",

    SEARCH_HISTORY = "SEARCH_HISTORY",

    SEARCH_DATA = "SEARCH_DATA",
    RESTAURANT_DATA = "RESTAURANT_DATA",
    SEARCH_LOCAL_STORAGE = "SEARCH_LOCAL_STORAGE"